---
- name: Générer site HTML pour GitHub Pages
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Créer répertoire site
      file:
        path: ./site
        state: directory

    - name: Générer page index.html
      copy:
        dest: ./site/index.html
        content: |
          <html>
            <head><title>Démo Ansible + GitHub Pages</title></head>
            <body>
              <h1>Site déployé via Ansible + GitHub Actions</h1>
              <p>Accessible publiquement grâce à GitHub Pages !</p>
            </body>
          </html>

    - name: Créer fichier .nojekyll
      copy:
        dest: ./site/.nojekyll
        content: ""
