---
- name: Déploiement d’un site statique avec GitHub Pages
  hosts: localhost
  gather_facts: false
  vars:
    site_dir: "./site"
    template_file: "./template/index.j2"
    output_file: "{{ site_dir }}/index.html"

  tasks:
    - name: Créer le dossier site s'il n'existe pas
      file:
        path: "{{ site_dir }}"
        state: directory

    - name: Récupérer le commit Git courant
      command: git rev-parse --short HEAD
      register: git_commit

    - name: Générer la date courante
      set_fact:
        deploy_date: "{{ lookup('pipe','date +%Y-%m-%d_%H-%M-%S') }}"

    - name: Générer le fichier HTML via template Jinja2
      template:
        src: "{{ template_file }}"
        dest: "{{ output_file }}"
      vars:
        commit: "{{ git_commit.stdout }}"
        date: "{{ deploy_date }}"

    - name: Vérifier que le fichier HTML est créé
      stat:
        path: "{{ output_file }}"
      register: html_stat

    - name: Afficher un message si le fichier est créé
      debug:
        msg: "Le fichier HTML a été généré avec succès : {{ output_file }}"
      when: html_stat.stat.exists
