---
- name: Déploiement d’un site statique avec GitHub Pages
  hosts: localhost
  gather_facts: no
  vars:
    site_dir: "./site"
    html_file: "{{ site_dir }}/index.html"
    image_url: "https://preview.redd.it/oynqiuq4a9k51.jpg?width=640&crop=smart&auto=webp&s=fb64945028dd789dc71031040a114f95025e65d7"

  tasks:

    - name: Créer le dossier site s'il n'existe pas
      file:
        path: "{{ site_dir }}"
        state: directory

    - name: Récupérer le commit courant
      command: git rev-parse --short HEAD
      register: git_commit
      ignore_errors: yes

    - name: Générer le fichier HTML via template Jinja2
      template:
        src: "templates/index.html.j2"
        dest: "{{ html_file }}"
      vars:
        commit_hash: "{{ git_commit.stdout | default('inconnu') }}"
        deploy_date: "{{ lookup('pipe','date +%d/%m/%Y %H:%M:%S') }}"
        github_repo: "{{ lookup('env','GITHUB_REPOSITORY') }}"
        demo_image: "{{ image_url }}"
