---
- name: Démo Ansible dans GitHub Actions avec accès public
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    - name: Créer un conteneur Nginx pour la démo
      community.docker.docker_container:
        name: demo-web
        image: nginx:latest
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "8080:80"   # exposer le port 80 du conteneur sur 8080 de l'hôte

    - name: Créer le répertoire /tmp/html
      file:
        path: /tmp/html
        state: directory
        mode: '0755'

    - name: Copier une page HTML de démo
      copy:
        dest: /tmp/html/index.html
        content: |
          <html>
            <head><title>Démo Ansible + Ngrok</title></head>
            <body>
              <h1>Conteneur web déployé via Ansible</h1>
              <p>Accessible publiquement grâce à Ngrok !</p>
            </body>
          </html>
