- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Créer le dossier du site
      file:
        path: site
        state: directory

    - name: Générer la page HTML
      template:
        src: templates/index.html.j2
        dest: site/index.html
