---
- name: Démo Ansible + Ngrok dans GitHub Actions
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    - name: Créer un conteneur Nginx pour la démo
      community.docker.docker_container:
        name: demo-web
        image: nginx:latest
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "8080:80"

    - name: Copier une page HTML directement dans le conteneur Nginx
      community.docker.docker_container_exec:
        container: demo-web
        command: >
          /bin/sh -c "echo '<html><head><title>Démo Ansible + Ngrok</title></head>
          <body><h1>Conteneur web déployé via Ansible</h1>
          <p>Accessible publiquement grâce à Ngrok !</p></body></html>'
          > /usr/share/nginx/html/index.html"

    - name: Créer un répertoire temporaire pour l'artefact (optionnel)
      file:
        path: /tmp/html
        state: directory
        mode: '0755'

    - name: Copier une page HTML pour artefact (optionnel)
      copy:
        dest: /tmp/html/index.html
        content: "<html><body>Demo Ansible + Ngrok</body></html>"
