---
- name: Déploiement d’un site statique avec GitHub Pages
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:

    - name: Créer le dossier site s'il n'existe pas
      file:
        path: ./site
        state: directory

    - name: Récupérer le commit Git courant
      command: git rev-parse --short HEAD
      register: git_commit_result

    - name: Générer la date courante
      command: date "+%d/%m/%Y %H:%M:%S"
      register: build_date_result

    - name: Générer le fichier HTML via template Jinja2
      template:
        src: templates/index.j2
        dest: site/index.html
      vars:
        git_commit: "{{ git_commit_result.stdout }}"
        build_date: "{{ build_date_result.stdout }}"

    - name: Initialiser le dépôt Git si nécessaire
      git:
        repo: "https://github.com/{{ github_user }}/{{ repo_name }}.git"
        dest: .
        init: yes
        update: yes

    - name: Ajouter l’origine distante si elle n’existe pas
      command: git remote add origin "https://github.com/{{ github_user }}/{{ repo_name }}.git"
      ignore_errors: yes
