name: Déploiement GitHub Pages avec Ansible

on:
  push:
    branches:
      - main  # Déploie quand tu pushes sur main

permissions:
  contents: write  # ⚠️ important pour que le bot puisse pousser sur gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Installer Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Exécuter le playbook
        run: ansible-playbook deploy.yml

      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
