name: Déploiement GitHub Pages via Ansible

on:
  push:
    branches:
      - main  # ou master selon ton repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer Python et Ansible
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Installer Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible jinja2

      # 3️⃣ Exécuter le playbook pour générer le site
      - name: Exécuter le playbook Ansible
        run: ansible-playbook deploy.yml

      # 4️⃣ Publier le contenu de ./site sur gh-pages
      - name: Publier sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./site
          # Le token Actions est automatiquement fourni par GitHub
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Branche cible pour GitHub Pages
          publish_branch: gh-pages
