name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # nécessaire pour push sur gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible playbook
        run: ansible-playbook deploy.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

      - name: Show GitHub Pages URL
        run: echo "https://$GITHUB_REPOSITORY.github.io/"
