name: Deploy with Ansible and expose publicly

on:
  push:
    branches: [ main ]

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Installer Ansible + Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible python3-docker docker.io jq unzip curl
          ansible-galaxy collection install community.docker

      - name: Lancer le playbook
        run: ansible-playbook -i inventory.ini deploy.yml

      - name: Installer ngrok
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
        run: |
          # Télécharger binaire ngrok (v3 puis fallback v2)
          set -e
          if curl -fsSL -o ngrok.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-linux-amd64.tgz; then
            tar -xzf ngrok.tgz
          else
            curl -fsSL -o ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
            unzip -o ngrok.zip
          fi
          sudo mv ngrok /usr/local/bin/ngrok
          ngrok config add-authtoken "$NGROK_AUTHTOKEN"

          - name: Démarrer le tunnel et publier l'URL
          id: tunnel
          shell: bash
          run: |
            set -euo pipefail
            nohup ngrok http 8080 --log=stdout > ngrok.log 2>&1 &
        
            # Attendre que l'API locale ngrok (4040) soit dispo
            for i in $(seq 1 30); do
              sleep 1
              if curl -fsS http://127.0.0.1:4040/api/tunnels >/dev/null 2>&1; then
                break
              fi
            done
        
            # Récupérer la première URL https via l'API locale
            URL="$(curl -s http://127.0.0.1:4040/api/tunnels \
              | jq -r '.tunnels[] | select(.proto=="https") | .public_url' \
              | head -n1)"
        
            # Fallback si l'API n'est pas prête : extraire depuis le log
            if [ -z "$URL" ] && [ -f ngrok.log ]; then
              URL="$(grep -oE 'https://[0-9a-zA-Z.-]*ngrok[^ ]*' ngrok.log | head -n1 || true)"
            fi
        
            test -n "$URL" || { echo "Impossible de trouver l'URL publique ngrok"; exit 1; }
        
            echo "$URL" > public_url.txt
            echo "Public URL: $URL"
            echo "public_url=$URL" >> "$GITHUB_OUTPUT"
            echo "🔗 Public URL: $URL" >> "$GITHUB_STEP_SUMMARY"
        
      - name: Uploader l'URL publique
        uses: actions/upload-artifact@v4
        with:
          name: public-url
          path: public_url.txt

      - name: Uploader la page web
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: /tmp/html/index.html

      - name: Laisser le tunnel ouvert 10 minutes (démo)
        run: sleep 600
