name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer Ansible + dépendances
      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      # 3️⃣ Lancer le playbook pour créer le conteneur web
      - name: Run Ansible playbook to generate HTML
        run: ansible-playbook deploy.yml

      # 4️⃣ Déployer la page HTML sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          # Optionnel : branch cible, défaut gh-pages
          # publish_branch: gh-pages
