name: Déploiement Ansible -> GitHub Pages

on:
  push:
    branches:
      - main  # Déclenchement sur push sur main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v3

      - name: Installer Python et uv
        run: |
          curl -sSf https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
          uv install ansible

      - name: Vérifier uv et ansible
        run: |
          uv --version
          ansible --version

      - name: Exécuter le playbook Ansible
        run: |
          uv run ansible-playbook -i localhost, deploy.yml

      - name: Publier sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          user_name: github-actions
          user_email: github-actions@users.noreply.github.com

      - name: Afficher l'URL GitHub Pages
        run: |
          echo "https://$(echo $GITHUB_REPOSITORY | cut -d'/' -f1).github.io/$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)/"
