name: Deploy with Ansible in SaaS mode

on:
  push:
    branches: [ main ]

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible + dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible python3-docker unzip curl jq
          ansible-galaxy collection install community.docker

      - name: Run Ansible playbook
        run: ansible-playbook -i inventory.ini deploy.yml

      - name: Download & setup Ngrok
        run: |
          curl -s https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -o ngrok.tgz
          tar -xzf ngrok.tgz
          sudo mv ngrok /usr/local/bin/
          ngrok version
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}

      - name: Start Ngrok tunnel (HTTP on port 8080)
        run: |
          nohup ngrok http 8080 --log=stdout > ngrok.log &
          sleep 5
          echo "----- Ngrok Tunnel Info -----"
          curl --silent http://127.0.0.1:4040/api/tunnels \
            | jq -r '.tunnels[] | select(.proto=="https") | .public_url' \
            | head -n1

      - name: Upload generated website
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: /tmp/html/index.html
